language: generic

sudo: false
os: linux
dist: trusty

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: change

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

git:
  depth: 10

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev
